# Made changes? Then: 
# ``conda env update --file pelican-conda-environment.yml``
name: pelican

dependencies:
  - python=3.6
  - cython
  - bpython
  - jupyter
  - pelican=3.7.1
  - matplotlib
  - black
  - beautifulsoup4
  - pip:
    - webassets
    - cssmin
    - bpython

