# Made changes? Then: 
# ``conda env update --file pelican-conda-environment.yml``
name: pelican
channels:
  - conda-forge

dependencies:
  - python=3.7.3
  - pelican=4.0.1
  - markdown
  - cython
  - jupyter
  - matplotlib
  - black
  - beautifulsoup4
  - pip
  - pip:
    - ptpython
    - webassets
    - cssmin

