# Made changes? Then:
# ``conda update -n base -c defaults conda``
# ``conda env update --file pelican-conda-environment.yml``
name: pelican
channels:
  - conda-forge

dependencies:
  - python>=3.7.3
  - pelican>=4.0.1
  - beautifulsoup4
  - black
  - cython
  - jupyter
  - nodejs
  - markdown
  - matplotlib
  - pillow
  - pip
  - pysvg-py3
  - pip:
    - ptpython
    - webassets
    - cssmin
    - cssutils

